### ISSUE TITLE
Profil korisnika

### ISSUE THREAD

**Issue by CommName** [CommName/AimPro#3]
Kreirati posebnu klasu za profil korisnika koja ima atribute (username, elo , hitratio) i nju proslediti prkeo wcf, umesto sadasnje klase user. HitRatio se dobija iz baze tako sto se uradi avrage za sve matcheve brojPogodka/ (brojPogodka + brojPromasaja). 
Kreirati posebnu wcf funkciju koja vraca istoriju svih metcveva i  implementirati prikaz za oba na klijentskoj strani. Mecevi da se prkizuju u obliku neke liste/tabele

**Comment by stefi51** [comment]
Klasa profil koja se salje preko wcf: ukupni promasaj, ukupni pogodci, ukupni broj meceva, elo, username, hitratio, niz mec statistika(10 ili manje).
Klasa mec statistika: type of game, broj poena u mecu, broj promasaja, broj pogodaka, rank na tom mecu.
